// export const listMenu = [
//   {
//     namaMenu: "Indomie Rebus",
//     kategori: "makanan",
//     hargaMenu: 8000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Indomie Goreng",
//     kategori: "makanan",
//     hargaMenu: 9000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Kopi Hitam Panas",
//     kategori: "minuman",
//     hargaMenu: 5000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Es Kopi Susu",
//     kategori: "minuman",
//     hargaMenu: 12000,
//     isAvailable: false,
//   },
//   {
//     namaMenu: "Teh Panas Manis",
//     kategori: "minuman",
//     hargaMenu: 5000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Es Teh Manis",
//     kategori: "minuman",
//     hargaMenu: 6000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Roti Bakar Coklat Keju",
//     kategori: "makanan",
//     hargaMenu: 15000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Nasi Goreng Spesial",
//     kategori: "makanan",
//     hargaMenu: 20000,
//     isAvailable: false,
//   },
//   {
//     namaMenu: "Mie Ayam",
//     kategori: "makanan",
//     hargaMenu: 18000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Gorengan (Per Biji)",
//     kategori: "makanan",
//     hargaMenu: 2000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Kopi Susu Panas",
//     kategori: "minuman",
//     hargaMenu: 10000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Es Jeruk",
//     kategori: "minuman",
//     hargaMenu: 8000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Jus Alpukat",
//     kategori: "minuman",
//     hargaMenu: 15000,
//     isAvailable: false,
//   },
//   {
//     namaMenu: "Kentang Goreng",
//     kategori: "makanan",
//     hargaMenu: 12000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Susu Jahe",
//     kategori: "minuman",
//     hargaMenu: 9000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Es Coklat",
//     kategori: "minuman",
//     hargaMenu: 10000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Indomie Kuah Soto",
//     kategori: "makanan",
//     hargaMenu: 9000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Telur Setengah Matang",
//     kategori: "makanan",
//     hargaMenu: 7000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Es Milo",
//     kategori: "minuman",
//     hargaMenu: 11000,
//     isAvailable: true,
//   },
//   {
//     namaMenu: "Mie Dok Dok",
//     kategori: "makanan",
//     hargaMenu: 14000,
//     isAvailable: false,
//   },
// ];

export const daftarMenu = [
  {
    kategori: "Makanan",
    menu: [
      {
        namaMenu: "Indomie Rebus",
        hargaMenu: 8000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?indomie",
      },
      {
        namaMenu: "Indomie Goreng",
        hargaMenu: 9000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?gorengan",
      },
      {
        namaMenu: "Roti Bakar Coklat Keju",
        hargaMenu: 15000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?roti",
      },
      {
        namaMenu: "Nasi Goreng Spesial",
        hargaMenu: 20000,
        isAvailable: false,
        gambarMenu: "https://source.unsplash.com/random/400x300/?nasigoreng",
      },
      {
        namaMenu: "Mie Ayam",
        hargaMenu: 18000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?mie",
      },
      {
        namaMenu: "Gorengan (Per Biji)",
        hargaMenu: 2000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?gorengan",
      },
      {
        namaMenu: "Kentang Goreng",
        hargaMenu: 12000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?kentang",
      },
      {
        namaMenu: "Indomie Kuah Soto",
        hargaMenu: 9000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?indomiesoto",
      },
      {
        namaMenu: "Telur Setengah Matang",
        hargaMenu: 7000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?telur",
      },
      {
        namaMenu: "Mie Dok Dok",
        hargaMenu: 14000,
        isAvailable: false,
        gambarMenu: "https://source.unsplash.com/random/400x300/?mie",
      },
    ],
  },
  {
    kategori: "Minuman",
    menu: [
      {
        namaMenu: "Kopi Hitam Panas",
        hargaMenu: 5000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?kopi",
      },
      {
        namaMenu: "Es Kopi Susu",
        hargaMenu: 12000,
        isAvailable: false,
        gambarMenu: "https://source.unsplash.com/random/400x300/?eskopi",
      },
      {
        namaMenu: "Teh Panas Manis",
        hargaMenu: 5000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?teh",
      },
      {
        namaMenu: "Es Teh Manis",
        hargaMenu: 6000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?esteh",
      },
      {
        namaMenu: "Kopi Susu Panas",
        hargaMenu: 10000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?kopisusu",
      },
      {
        namaMenu: "Es Jeruk",
        hargaMenu: 8000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?esjeruk",
      },
      {
        namaMenu: "Jus Alpukat",
        hargaMenu: 15000,
        isAvailable: false,
        gambarMenu: "https://source.unsplash.com/random/400x300/?jusalpukat",
      },
      {
        namaMenu: "Susu Jahe",
        hargaMenu: 9000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?susu",
      },
      {
        namaMenu: "Es Coklat",
        hargaMenu: 10000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?escoklat",
      },
      {
        namaMenu: "Es Milo",
        hargaMenu: 11000,
        isAvailable: true,
        gambarMenu: "https://source.unsplash.com/random/400x300/?milo",
      },
    ],
  },
];
